In [1]:
#Loading the library with the iris dataset
from sklearn.datasets import load_iris

#Loading scikit's random forest classifer library
from sklearn.ensemble import RandomForestClassifier

#Loading Pandas
import pandas as pd

#Loading numpy
import numpy as np

#Setting random seed
np.random.seed(0)

In [3]:
#creating an object called iris with the iris data
iris = load_iris()

#creating a dataframe with the four feature variables
df = pd.DataFrame(iris.data, columns = iris.feature_names)

#Viewing the top 5 rows
# print(iris)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
#Adding a new column for the species name
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

#viewing the top 5 names
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [5]:
#Creating Test and Train Data
df['is_train'] = np.random.uniform(0,1,len(df)) <= .75

#Viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [7]:
#Creating dataframes with test rows and training rows
train, test = df[df['is_train'] == True], df[df['is_train'] == False]

#Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))

Number of observations in the training data: 118
Number of observations in the test data: 32


In [8]:
#create a list of the feature column's names
features = df.columns[:4]

#view features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [9]:
#Converting each species name into digits
y = pd.factorize(train['species'])[0]

#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
#Creating a Random Forest Classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

#Training the classifier
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [11]:
#Applying the trained classifier to the test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [12]:
#Viewing te predicted probabilities of the first 10 observation
clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.67, 0.33],
       [0.  , 1.  , 0.  ],
       [0.  , 0.82, 0.18],
       [0.  , 0.03, 0.97],
       [0.  , 0.42, 0.58],
       [0.  , 0.99, 0.01],
       [0.  , 0.96, 0.04]])

In [16]:
#Mapping names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

#View the PREDICTED species for the first 25 observations
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [15]:
#Viewing the ACTUAL Species for the first five observations
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [17]:
#Creating confusion matrix
pd.crosstab(test['species'], preds, rownames = ['Actual Species'], colnames = ['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [27]:
preds = iris.target_names[clf.predict(test[features])[12:18]]
# preds = iris.target_names[clf.predict([[5.0,3.6,1.4,0.2],[4.9, 3.0,1.4,0.2]])]

preds

array(['setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica'], dtype='<U10')